src/src/objects/FileExplorerFile__c.object
<CustomObject>
    <description>Store a hierarchical structure of content documents</description>
    <fields>
        <fullName>ContentDocumentId__c</fullName>
        <description>Content Document ID</description>
        <externalId>true</externalId>
        <label>Content Document Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentSize__c</fullName>
        <label>Content Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FileExtension__c</fullName>
        <description>File Extension</description>
        <inlineHelpText>File Extension</inlineHelpText>
        <label>File Extension</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>File folder</description>
        <inlineHelpText>File folder</inlineHelpText>
        <label>Folder</label>
        <referenceTo>FileExplorerFolder__c</referenceTo>
        <relationshipLabel>Files</relationshipLabel>
        <relationshipName>File_Explorer_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>File label</description>
        <externalId>true</externalId>
        <inlineHelpText>File label</inlineHelpText>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LinkedEntityId__c</fullName>
        <description>Linked Entity Id</description>
        <externalId>true</externalId>
        <label>Linked Entity Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>File Explorer File</label>
    <nameField>
        <displayFormat>FILEX-{0000000}</displayFormat>
        <label>File Explorer File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Explorer Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/src/objects/FileExplorerFolder__c.object
<CustomObject>
    <description>Store a hierarchical structure of content documents</description>
    <fields>
        <fullName>Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Folder</label>
        <referenceTo>FileExplorerFolder__c</referenceTo>
        <relationshipLabel>Folders</relationshipLabel>
        <relationshipName>File_Explorer_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>Folder Label</description>
        <externalId>true</externalId>
        <inlineHelpText>Folder Label</inlineHelpText>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LinkedEntityId__c</fullName>
        <description>Linked Entity Id</description>
        <externalId>true</externalId>
        <inlineHelpText>Linked Entity Id</inlineHelpText>
        <label>Linked Entity Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>File Explorer Folder</label>
    <nameField>
        <displayFormat>FEF-{0000000}</displayFormat>
        <label>File Explorer Folder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>File Explorer Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/qsydFileExplorerTest.cls
/**
 * :
 * @Last Modified On   : 5/3/2020, 7:32:31 PM
 * @Modification Log   :
 * Ver       Date            Author      		    Modification
 **/
@IsTest
global with sharing class qsydFileExplorerTest {
    private static final String SIG_B64 = 'aSBhbSBhIHNpZ25hdHVyZQ==';
    private static Account a;
    private static qsyd_File fileItem;
    private static qsyd_FileList fileItemList;
    private static qsyd_Folder folderItem;
    private static qsyd_FolderList folderItemList;

    @TestSetup
    private static void setupTestData() {
        fileItemList = new qsyd_FileList();
        folderItemList = new qsyd_FolderList();

        // Create LinkedEntity Record
        a = new Account(Name = 'TestAccount');
        INSERT a;

        //Create ContentVersion Record 
        ContentVersion contentVersion = new ContentVersion(
                Title = 'Penguins',
                PathOnClient = 'Penguins.jpg',
                VersionData = Blob.valueOf(SIG_B64),
                IsMajorVersion = true
        );
        insert contentVersion;
        List<ContentDocument> contentDocumentList = [
                SELECT Id,
                        Title,
                        ContentSize,
                        LatestPublishedVersionId
                FROM ContentDocument
                WHERE LatestPublishedVersionId = :contentVersion.Id
        ];

        //Create ContentDocumentLink Record 
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.LinkedEntityId = a.id;
        cdl.ContentDocumentId = contentDocumentList[0].Id;
        cdl.shareType = 'V';
        INSERT cdl;

        //Create Folder Record
        FileExplorerFolder__c qFolder = new FileExplorerFolder__c(LinkedEntityId__c = a.Id, Label__c = 'qFolder');
        INSERT qFolder;

        fileItem = new qsyd_File(
                null,
                qFolder.Id,
                'qFile',
                contentDocumentList[0].Id,
                a.Id,
                'jpg',
                'jpg',
                UserInfo.getUserId(),
                'tags',
                contentDocumentList[0].ContentSize,
                null);
    }

    @IsTest
    private static void given_newFile_when_loadItem_success() {
        setupTestData();
        Test.startTest();

        fileItem.convertToCanonical()
                .save();

        List<FileExplorerFile__c> qFiles = [
                SELECT Id,
                        ContentDocumentId__c,
                        Folder__c,
                        Label__c,
                        LinkedEntityId__c,
                        FileExtension__c,
                        ContentSize__c
                FROM FileExplorerFile__c
                ORDER BY LastModifiedDate DESC
                LIMIT 1
        ];

        Test.stopTest();

        System.assertEquals(1, qFiles.size());
    }


    @IsTest
    private static void given_newFileItemList_when_convertedToCanonical_success() {
        List<FileExplorerFile__c> canonicalFiles;

        setupTestData();

        Test.startTest();

        canonicalFiles = fileItemList.load(new List<qsyd_File>{
                fileItem
        }).convertToCanonical()
                .getCanonicalList();

        Test.stopTest();

        System.assertEquals(1, canonicalFiles.size());
    }

    @IsTest
    private static void given_newFolderItemList_when_convertedToLogical_success() {
        List<qsyd_Item> logicalFolders;

        setupTestData();

        Test.startTest();

        logicalFolders = folderItemList
                .retrieve(a.Id)
                .convertToLogical()
                .getLogicalList();

        Test.stopTest();

        System.assertEquals(1, logicalFolders.size());
    }

    @IsTest
    private static void given_newFolderItemList_when_convertedToCanonical_success() {
        List<FileExplorerFolder__c> canonicalFolders;

        setupTestData();

        Test.startTest();

        folderItemList = new qsyd_FolderList(new List<qsyd_Item>{
                fileItem
        });

        canonicalFolders = folderItemList
                .retrieve(a.Id)
                .convertToCanonical()
                .getCanonicalList();

        Test.stopTest();

        System.assertEquals(2, canonicalFolders.size());
    }
}